### ISSUE TITLE
Améliorer la visibilité du bouton pour rejoindre un Groupe

### ISSUE THREAD

**Issue by NortonleChat** [Tilotiti/Pokemon#17]
L'icône actuelle est très petite et ne saute pas aux yeux quand on est sur la page d'un groupe. Un bouton plus gros/coloré serait pas de trop pour que les gens sachent comment rejoindre un groupe (au moins) la première fois. ;)

**Comment by Tilotiti** [comment]
Done !

**Comment by Tilotiti** [comment]
Mais à savoir que si le site marche, il aura le droit à une vraie couche de design.
