### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by d3vilsn0w** [Tilotiti/Pokemon#24]
A connexion error occured. Your Google Logins are not valid or Pokemon Go server are crashed. If not, open your Google Account here : https://g.co/allowaccess.

Everytime i login. This happens. Any idea where is the problem?

**Comment by Tilotiti** [comment]
Have you got à double-authentification process on your Google account? It's not compatible with the API.

If not, just click on the link provided, login, accept, then retry fiew minutes after.

**Comment by Tilotiti** [comment]
Found it ! If you have the 2 steps authentification, just click here : https://security.google.com/settings/security/apppasswords

And make a unique password for the application. It will work !

**Comment by d3vilsn0w** [comment]
I know that method. I tried it buddy. It works on Bot. but whenever i try it on a server with your script. It doesn't let me login :/

**Comment by Tilotiti** [comment]
It worked with one of my friends few minutes ago.

Are you trying the good password ?

**Comment by d3vilsn0w** [comment]
pokemongo.sharehoot.com here it is where i installed it.

**Comment by d3vilsn0w** [comment]
It doesn't work with either Ptc I'd love if you could help me out fixing it.

**Comment by Tilotiti** [comment]
Then, your nodeJS script might have a problem, i can't connect either, but it work on mine.

**Comment by d3vilsn0w** [comment]
What do you suggest? I need to get it workiing :/ Really loved the work.

**Comment by Tilotiti** [comment]
Try : 

```
$ cd /[you-project]
$ node bin/refresh.js [your username] [your password]
```

What does it tell you ?

**Comment by d3vilsn0w** [comment]
$ node bin/refresh.js [your username] [your password]
What password username do i have to enter. Ptc?

**Comment by Tilotiti** [comment]
You PTC username/password

**Comment by d3vilsn0w** [comment]
{ [StopError: Status code 403 received from HTTPS request]
  name: 'StopError',
  message: 'Status code 403 received from HTTPS request' }

**Comment by Tilotiti** [comment]
Then it's a Pogobuf issue ! Something is wrong with your authentification.

I can't help you further, but here is the github you need :

https://github.com/cyraxx/pogobuf

**Comment by Tilotiti** [comment]
It's a known issue, you are not alone : https://github.com/cyraxx/pogobuf/issues/68

**Comment by d3vilsn0w** [comment]
Hopefully it'll get fixed or at least proxy support would be sick if it is possible. Not so familiar with NodeJS.

**Comment by Tilotiti** [comment]
And did you tried locally ?

**Comment by d3vilsn0w** [comment]
I haven't but it seems like it is happening bc IP ranges ban. I am hosted on DigitalOcean. I needed to get it up on server.

**Comment by Tilotiti** [comment]
https://github.com/cyraxx/pogobuf/wiki/Blocked-server-ISPs

Yeap :s Sorry for that ...

**Comment by d3vilsn0w** [comment]
Anyway. is it possible for developer to make it work with Proxies?

**Comment by Tilotiti** [comment]
I think so, but I couln't help you with that. I'm not familiar with proxy servers.

**Comment by d3vilsn0w** [comment]
Thank you for helping me debugging the issue. I'll close it 👍 Have a great day mate.

**Comment by Tilotiti** [comment]
You too

**Comment by d3vilsn0w** [comment]
@Tilotiti I fixed it with proxies new response. 
{"player":{"level":1,"xp":0,"km":0,"discovered":0,"catched":0,"evolved":0,"prevLevel":"0","nextLevel":"1000","username":"futhoot+step","team":0,"sign":"1470766041"},"pokedex":[]}

It still says the same on the site.

**Comment by Tilotiti** [comment]
The response says it's working ! But as you don't have any pokemon yet, it must be an issue somewhere. Can you catch at least one ?

**Comment by d3vilsn0w** [comment]
I tried after catching some pokemons still the same. :(

**Comment by Tilotiti** [comment]
Can you dump the process return In AppBundle:Service:Player please while trying to log In ?

**Comment by d3vilsn0w** [comment]
I don't have any idea how to do it :/

**Comment by d3vilsn0w** [comment]
Response was 127
Pokemongo.sharehoot.com
You can see it there i added 
        $process = new Process("/usr/local/bin/node ".**DIR**.'/../../../bin/refresh.js '.$params);
print_r($process->run());
die();

**Comment by Tilotiti** [comment]
Not enought ;)

/web/app_dev.php : remove (temporarly) lines 13 to 19.

Add, in /src/AppBundle/Service/Player.php, line 25 :

```
dump($process->getOutput());
```

Try to connect from /app_dev.php/login

Clic on the green "200" at the bottom of the page (Symfony Debug bar).

Then click on "Latest 10" on the top left.

You'll find a line with the column "method" to "POST", click on its token at the end of the line.

Choose "Debug" on the left menu.

Paste the debug.

**Comment by d3vilsn0w** [comment]
There is no data response in there but that POST request had a HTTP Status 302.

**Comment by d3vilsn0w** [comment]
Add, in /src/AppBundle/Service/Player.php, line 25 :

dump($process->getOutput());

Line 25 Are you sure? I tried but it doesn't work

**Comment by Tilotiti** [comment]
35, sorry... Basic PHP.

**Comment by d3vilsn0w** [comment]
Tried on that as well. No data in debug

**Comment by d3vilsn0w** [comment]
![image](https://cloud.githubusercontent.com/assets/19762306/17533507/a9919bae-5ea2-11e6-9259-38bf13406317.png)

**Comment by Tilotiti** [comment]
Last try : can you replace getOutput in your dump by getErrorOutput ?

**Comment by d3vilsn0w** [comment]
![image](https://cloud.githubusercontent.com/assets/19762306/17538140/69fb0426-5ec0-11e6-8fda-19e27041ca09.png)

I think we know now the issue?

**Comment by d3vilsn0w** [comment]
My location to refresh.js
/home/shoot/public_html/pokemon/Pokemon/bin/refresh.js

```
    $process = new Process("/usr/local/bin/node ".__DIR__.'/../../../bin/refresh.js '.$params);
    $process->run();
```

dump($process->getErrorOutput());

My code.

**Comment by Tilotiti** [comment]
Seems like node is not installed, not at the right place or not exécutable by apache user.

**Comment by d3vilsn0w** [comment]
When i installed nodeJS. I installed it as a root. How can i give permission to user "Shoot" ?

**Comment by Tilotiti** [comment]
To find the good path of nodejs, try : 

```
$ which nodejs
```

Replace the path of node in Player.php by the good one.

I can't halp you any further.

**Comment by d3vilsn0w** [comment]
root@root [~]# $ which nodejs
-bash: $: command not found

**Comment by d3vilsn0w** [comment]
Sorry for annoying you way too much :/

**Comment by Tilotiti** [comment]
$ mean "start of the line". Don't copy that.

**Comment by d3vilsn0w** [comment]
I swear i don't know why i copied that xD

**Comment by d3vilsn0w** [comment]
No response. Its blank.

**Comment by d3vilsn0w** [comment]
I'm trying something. I'll let you know. You've no idea how bad i want it to work :P

**Comment by d3vilsn0w** [comment]
root@root [/usr/src/node-v0.10.4]# which node
/usr/local/bin/node

**Comment by Tilotiti** [comment]
And now ? Does it work ?

**Comment by d3vilsn0w** [comment]
![image](https://cloud.githubusercontent.com/assets/19762306/17548621/549dfb3e-5f0a-11e6-8149-649eb018d5ea.png)

**Comment by Tilotiti** [comment]
You did'n installed the node dependencies : 

```
$ npm install
```

**Comment by Tilotiti** [comment]
Sorry : 

```
$ cd [your-path]
$ npm install
```

**Comment by d3vilsn0w** [comment]
root@root [/home/shoot/public_html/pokemon/Pokemon]# npm install
npm http GET https://registry.npmjs.org/pogobuf
npm http 200 https://registry.npmjs.org/pogobuf
npm ERR! Error: No compatible version found: pogobuf@'^1.4.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.1.0","1.2.0","1.3.0","1.4.0","1.5.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/shoot/public_html/pokemon/Pokemon
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/shoot/public_html/pokemon/Pokemon/npm-debug.log
npm ERR! not ok code 0
root@root [/home/shoot/public_html/pokemon/Pokemon]# 

RIP

**Comment by d3vilsn0w** [comment]
I'll try reinstalling the script.

**Comment by Tilotiti** [comment]
Try just : 

```
$ npm install pogobuf
```

**Comment by d3vilsn0w** [comment]
[~/public_html/pokemon/Pokemon]# npm install pogobuf
npm http GET https://registry.npmjs.org/pogobuf
npm http 304 https://registry.npmjs.org/pogobuf
npm ERR! Error: No compatible version found: pogobuf@'^1.4.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.1.0","1.2.0","1.3.0","1.4.0","1.5.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pogobuf"
npm ERR! cwd /home/shoot/public_html/pokemon/Pokemon
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/shoot/public_html/pokemon/Pokemon/npm-debug.log
npm ERR! not ok code 0
shoot@[~/public_html/pokemon/Pokemon]#

**Comment by Tilotiti** [comment]
Your nodeJS is wayyyyyyyyy too old.

For upgrading :

```
$ npm cache clean -f
$ npm install -g n
$ n stable
$ node -v
```

Then you should have node v6.2.2 installed.

Try again then.

**Comment by d3vilsn0w** [comment]
root@root [~]# npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.
root@root [~]# 
Am i suppose to do at cd / ?

**Comment by Tilotiti** [comment]
Anywhere, "-g" means "global"

**Comment by d3vilsn0w** [comment]
root@root [~]# node -v
v6.2.2

**Comment by Tilotiti** [comment]
Now ...

```
$ cd [your-path]
$ npm install
```

Then it should be working ...

**Comment by d3vilsn0w** [comment]
![image](https://cloud.githubusercontent.com/assets/19762306/17550331/196b064e-5f12-11e6-89da-de7322d7e6bf.png)

Couldn't be more happier :) <3 Thanks a lot mate.

**Comment by Tilotiti** [comment]
You are welcome.
Happy to see my work enjoyed.

If you want to keep this project up to date, don't hesitate to automatise the deployment : 

https://github.com/Tilotiti/Symfony-Deploy

You can also fork the project to do your own stuff and contribute to the main repository.

And of course, enjoy the official website : https://www.poke-rank.com (and share with your friends).

**Comment by d3vilsn0w** [comment]
Thanks mate. well if i wanna update the script in future. Do i need to follow it https://github.com/Tilotiti/Symfony-Deploy ?

**Comment by Tilotiti** [comment]
Not necesseraly, it's just an automatisation process.

If you want to update it, you'll have to do this : 

```
$ cd [your-project] # Go to your project
$ git reset --hard origin/master # Cancel any non-pushed local modification for preventing from conflicts
$ git-pull # Get the newest code
$ bin/console doctrine:schema:update --force # Update the database
$ composer update # Update dependencies (it's very long ... So sometimes, skip it ...)
$ bin/console cache:clear -e=prod # Clear prod cache
```

And you are done !

**Comment by d3vilsn0w** [comment]
Great. What are the notifications for?

**Comment by d3vilsn0w** [comment]
An error 500 When accoount is not logged in and this error happens

http://pokemongo.sharehoot.com/player/futhoot+step

**Comment by d3vilsn0w** [comment]
After logging in any account and it works.

**Comment by Tilotiti** [comment]
Your server missing the PHP5-Intl extension. 

```
$ apt-get install php5-intl
$ service apache2 restart
```

**Comment by d3vilsn0w** [comment]
Last - "Great. What are the notifications for?"

**Comment by Tilotiti** [comment]
For now, only for the groups. If someone want to join your group, you'll have notifications.
Others features are coming.

**Comment by d3vilsn0w** [comment]
You up?

**Comment by d3vilsn0w** [comment]
root@root [/home/shoot/public_html/pokemon/Pokemon]# git reset --hard origin/master
HEAD is now at 29f61fd responsive
root@root [/home/shoot/public_html/pokemon/Pokemon]# git-pull
-bash: git-pull: command not found
root@root [/home/shoot/public_html/pokemon/Pokemon]#

**Comment by d3vilsn0w** [comment]
I did git pull and it worked. 

root@root [/home/shoot/public_html/pokemon/Pokemon]# bin/console doctrine:schema:update --force 

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  The service "player" has a dependency on a non-existent parameter "node".

**Comment by Tilotiti** [comment]
```
& composer update
```

**Comment by d3vilsn0w** [comment]
I've done it. I'd be very thankful. if you could remove my user from Poke-Rank. "steptorres"

**Comment by d3vilsn0w** [comment]
Whenever i try to change data. in "base.html.twig". Those Hyperlinks and all. It doesn't work. They get saved in file but on site. Your links appears. Poke-rank

**Comment by d3vilsn0w** [comment]
@Tilotiti

**Comment by d3vilsn0w** [comment]
Thats the only issue last i am facing. Please if you could tell me something. I'd love it.

**Comment by d3vilsn0w** [comment]
Please?

**Comment by d3vilsn0w** [comment]
Fixed everything else mate. 

Now just one error in app-dev

RuntimeException in ClassCollectionLoader.php line 248:
Failed to write cache file "/home/shoot/public_html/pokemon/Pokemon/var/cache/dev/classes.php".
in ClassCollectionLoader.php line 248
at ClassCollectionLoader::writeCacheFile('/home/shoot/public_html/pokemon/Pokemon/var/cache/dev/classes.php', '<?php namespace Symfony\Component\EventDispatcher { interface EventSubscriberInterface { public static function getSubscribedEvents(); } } namespace Symfony\Component\HttpKernel\EventListener { use Symfony\Component\HttpKernel\Event\GetResponseEvent; use Symfony\Component\HttpKernel\KernelEvents; use Symfony\Component\EventDispatcher\EventSubscriberInterface; abstract class SessionListener implements EventSubscriberInterface { public function onKernelRequest(GetResponseEvent $event) { if (!$event->isMasterRequest()) { return; } $request = $event->getRequest(); $session = $this->getSession(); if (null === $session || $request->hasSession()) { return; } $request->setSession($session); } public static function getSubscribedEvents() { return array( KernelEvents::REQUEST => array('onKernelRequest', 128), ); } abstract protected function getSession(); } } namespace Symfony\Bundle\FrameworkBundle\EventListener { use Symfony\Component\HttpKernel\EventListener\SessionListener as BaseSessionListener; use Symfony\Component\DependencyInjection\ContainerInterface; class SessionListener extends BaseSessionListener { private $container; public function __construct(ContainerInterface $container) { $this->container = $container; } protected function getSession() { if (!$this->container->has('session')) { return; } return $this->container->get('session'); } } } namespace Symfony\Component\HttpFoundation\Session\Storage { use Symfony\Component\HttpFoundation\Session\SessionBagInterface; interface SessionStorageInterface { public function start(); public function isStarted(); public function getId(); public function setId($id); public function getName(); public function setName($name); public function regenerate($destroy = false, $lifetime = null); public function save(); public function clear(); public function getBag($name); public function registerBag(SessionBagInterface $bag); public function getMetadataBag(); } } namespace Symfony\Component\HttpFoundation\Session\Storage { use Symfony\Component\HttpFoundation\Session\SessionBagInterface; use Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler; use Symfony\Component\HttpFoundation\Session\Storage\Proxy\AbstractProxy; use

**Comment by Tilotiti** [comment]
This project is licensed. You have to keep the credits on it (in the footer).

Thank you.
