### ISSUE TITLE
Cannot login PTC or Google account

### ISSUE THREAD

**Issue by NZX-DeSiGN** [Tilotiti/Pokemon#29]
Hello,

I've followed the install procedure in the Readme, but I can't login any account. I also must access to the web folder to access to the site (htaccess related I think : installation may be not completed ?) 

The command below return me the good informations. Is there a node or php command to run to complete the install ?

```
node bin/refresh.js [your username] [your password]
```

Configuration : Windows 10 + EasyPHP + PHP7 + MySQL

Thanks for you help,
Nicolas

**Comment by Tilotiti** [comment]
It's a symfony project, so your vhost must target the web folder.

**Comment by NZX-DeSiGN** [comment]
Ok thanks, I've just seen it on a symfony thread, I've only used Phalcon PHP framework. 
My problem was because I'm on Windows and the node path and spaces in refresh.js path bug the command.

``` php
        $process = new Process("/usr/local/bin/node ".__DIR__.'/../../../bin/refresh.js '.$params);
```

Temporary fixed with :

``` php
        $process = new Process("node \"".__DIR__.'/../../../bin/refresh.js" '.$params);
```

Bug I've a second problem, www.site.com/player/xxxx, get me a 500 internal error. Have you a track ?

Edit : Ok i'ts only when I select the French language.

Thanks (and sorry for my english)
Nicolas

**Comment by Tilotiti** [comment]
You must install the PHP5-Intl extension.

**Comment by NZX-DeSiGN** [comment]
Perfect, everything works, thank you !
