### ISSUE TITLE
Statistiques de jeu avancées

### ISSUE THREAD

**Issue by RaoulDeLimesy** [Tilotiti/Pokemon#33]
Hello ! Pour en savoir plus sur le rythme auquel on progresse, je propose de mettre en place un petit menu statistiques ou autre qui pourrait comprendre :
- Des statistiques consolidées sur une période donnée
  - par joueur (et éventuellement par équipe)
  - selon différents critères : XP, Km, Pokédex, Capturés, Evolués
  - unité de temps : choix entre jours, semaines et mois
- Des courbes/indicateurs de progression sur chacun de ces critères, en valeur absolue et en pourcentage

Dans le même ordre d'idée (mais peut-être plutôt en page d'accueil ou autre), on pourrait imaginer avoir un "top de la semaine", par exemple top 3 des groupes/joueurs/équipes (jaune/rouge/bleu) ayant le plus progressé cette semaine (ex : randonneur de la semaine pour celui qui a parcouru le plus de kilomètres...).

**Comment by Tilotiti** [comment]
J'aimerais beaucoup pour le coup, j'avais commencé à le faire, le problème est que ces données statistiques ne sont viables que si les utilisateurs viennent se connecter tous les jours, voir tous les soirs à 23h59. Je n'ai pas la possibilité de recharger leurs données pour eux, ne sauvegardant pas les mots de passe.

Donc on pourrait historiser des données quotidiennement, mais les données seront approximatives.

Si le site marche suffisamment bien, ça donnera une idée convenable de la vraie progression des gens.

A tester donc !

**Comment by Tilotiti** [comment]
J'ai mis en place l'enregistrement des données. J'attends maintenant d'avoir un peu d'historic avant de les afficher.

Et donc, comme prévenu, il n'enregistre que les données qui ont été mises à jour dans la journée ! Il faut venir tous les jours ;)

**Comment by Tilotiti** [comment]
Ca t'irait ça ?

**Comment by RaoulDeLimesy** [comment]
Très bien, merci ! Un détail quand même : les dates en abscisse sont peu lisibles.
